#!/bin/sh
# Gemini CLI hook wrapper — adapts Claude hook protocol to Gemini
# Generated by converter. Original script is not modified.

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)

# Provide extensionPath env var (Gemini doesn't set it; scripts may reference it)
extensionPath="$(cd "$SCRIPT_DIR/.." && pwd)"
export extensionPath

# Run the original script, capture output and exit code
output=$("$SCRIPT_DIR/hooks-stop.sh" 2>/dev/null)
exit_code=$?

if [ $exit_code -eq 0 ] && [ -z "$output" ]; then
  # Allow path: original outputs nothing — Gemini needs JSON
  printf '{"decision":"allow"}\n'
  exit 0
fi

# Block/decision path: forward JSON output, exit 0
# Gemini: exit 0 = parse JSON decision, exit 1 = warning (non-fatal), exit 2 = emergency brake
printf '%s\n' "$output"
exit 0
